//
// Created by ash on 11/14/20.
//

#ifndef FINAL_PROJECT_ASH_MAHERIYA_NEURAL_NETWORK_APP_H
#define FINAL_PROJECT_ASH_MAHERIYA_NEURAL_NETWORK_APP_H

class NeuralNetworkApp {};

#endif // FINAL_PROJECT_ASH_MAHERIYA_NEURAL_NETWORK_APP_H
